[package]
name = "euxre/hinomori"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[place]
shared-packages = "game.ReplicatedStorage.Packages"
server-packages = "game.ServerScriptService.ServerPackages"

[dependencies]
Signal = "sleitnick/signal@2.0.3"
Janitor = "howmanysmall/janitor@1.1.8"
Sift = "csqrl/sift@0.0.11"
Networker = "leifstout/networker@0.3.1"
DataServiceTyped = "leifstout/dataservicetyped@1.0.4"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.3"
